### ISSUE TITLE
Swagger and .NET Core 3.0 preview

### ISSUE THREAD

**Issue by QuinntyneBrown** [andreyleskov/MightyCalc#4]
Were you able to get swagger to work with 3.0.0-preview-19075-0444?

I noticed you are doing some unique with the static files? Is that a work around to get swagger documentation working?

**Comment by andreyleskov** [comment]
Hello Quinntyne,

You've spotted the pain point - swagger UI doesn't play well with 3.0.0-preview runtime image.
The workaround is to use 3.0.0-preview sdk image for runtime, or a deprecated image from microsoft/dotnet:3.0-aspnetcore-runtime instead of latest mcr.microsoft.com/dotnet/core/** Ugly, but works. 
This app uses API definition in OpenAPI format to [generate](https://github.com/andreyleskov/MightyCalc/blob/master/MightyCalc.API/Dockerfile#L17) controllers and C# API client out of it. It is done to keep [API definition ](https://github.com/andreyleskov/MightyCalc/blob/master/MightyCalc.API/MightyCalcAPI.yaml)as a source of truth instead of controllers as a source of truth. I like this approach for API-first development when we define domain and language and build the API right after, without any implementation.

**Comment by QuinntyneBrown** [comment]
This package seems to work for me. Swashbuckle.AspNetCore 5.0.0-rc2
